**Function Description:**

In [2]:
import pandas as pd
import numpy as np

**Q. 1**

In [2]:
print(f"Version of Pandas: {pd.__version__}")

Version of Pandas: 2.2.2


**Q. 2**

In [3]:
data = pd.read_csv('laptops.csv')
# print number of records
print(len(data))

2160


**Q. 3**

In [4]:
#  print number of types of laptops
print(len(data['Brand'].value_counts()))

27


**Q.4** 

In [5]:
print(data.isnull().sum())

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64


**Q. 5**

In [6]:
print(data.groupby("Brand")["Final Price"].max()['Dell'])

3936.0


**Q. 6**

In [7]:
print(data['Screen'].median()) # median

15.6


Most frequent value

In [8]:
most_freq = data['Screen'].mode()
print(most_freq) # most common screen size

0    15.6
Name: Screen, dtype: float64


In [9]:
filled_data = data['Screen'].fillna(most_freq)
print(filled_data.median())

15.6


**Q. 7**

In [10]:
print(data[data['Brand'] == 'Innjoo']) # laptops of brand Innjoo


                                                 Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128 

In [11]:
print(data[data['Brand'] == 'Innjoo'][["RAM","Storage","Screen"]]) # laptops of brand Innjoo with columns RAM, Storage, Screen

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1


In [12]:
X = data[data['Brand'] == 'Innjoo'][["RAM","Storage","Screen"]].to_numpy()  # laptops of brand Innjoo with columns RAM, Storage, Screen as numpy array   
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [13]:
XTX = X.T.dot(X) # X transpose times X
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [14]:
XTX_inv = np.linalg.inv(XTX) # inverse of XTX
print(XTX_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [15]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [16]:
result = XTX_inv.dot(X.T).dot(y) # (XTX)^-1 * XT * y
print(f"result: {result} with sum {result.sum()}")

result: [45.58076606  0.42783519 45.29127938] with sum 91.2998806299557
